### ISSUE TITLE
Compare lower case

### ISSUE THREAD

**Issue by erema** [ermch1kk/telegram-chat-bot#1]
Fix condition lower case. Condition will return always false.

**Comment by ermch1kk** [comment]
Thanks for the feedback! I started solving the problem.

**Comment by ermch1kk** [comment]
> Fix condition lower case. Condition will return always false.

Thanks for the feedback! I started solving the problem.

**Comment by ermch1kk** [comment]
> Fix condition lower case. Condition will return always false.

The problem is solved!![image](https://github.com/user-attachments/assets/a6f49021-2219-4cc8-8ac5-5c67aaa5ef1c)
